### ISSUE TITLE
2.10 public release introduces "KeyError: 'testcase_name'" warnings

### ISSUE THREAD

**Issue by bcfriesen** [eth-cscs/reframe#138]
Starting with commit 24b605e ("Reframe 2.10 public release"), my tests now generate huge amounts of warning messages like the following:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'testcase_name'
Call stack:
  File "/global/homes/f/friesen/reframe/bin/reframe", line 6, in <module>
    cli.main()
  File "/global/u2/f/friesen/reframe/reframe/frontend/cli.py", line 417, in main
    printer.info(runner.stats.failure_report())
  File "/global/u2/f/friesen/reframe/reframe/frontend/printer.py", line 113, in info
    self._logger.info(msg)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/logging/__init__.py", line 1634, in info
    self.log(INFO, msg, *args, **kwargs)
  File "/global/u2/f/friesen/reframe/reframe/core/logging.py", line 225, in log
    super().log(level, msg, *args, **kwargs)
```
In commits prior to this one, these warnings did not occur. Note that the functionality appears to be unchanged and the tests run as normal.

Looking through the changes in this commit, it seems there are several places where `testcase_name` was either removed altogether, or replaced with `check_info`. These include:

```
@@ -152,20 +152,6 @@ class Logger(logging.Logger):

     def makeRecord(self, name, level, fn, lno, msg, args, exc_info,
                    func=None, extra=None, sinfo=None):
-        # Setup dynamic fields of the check
-        if self.check:
-            testcase_name = self.check.name
-            if self.check.job:
-                extra['check_jobid'] = self.check.job.jobid
-
-            if self.check.current_partition:
-                testcase_name += '@%s' % self.check.current_partition.fullname
-
-            if self.check.current_environ:
-                testcase_name += ' using %s' % self.check.current_environ.name
-
-            extra['testcase_name'] = testcase_name
-
```
as well as here:
```
@@ -206,12 +192,11 @@ class LoggerAdapter(logging.LoggerAdapter):
             {
                 'check_name': check.name if check else 'reframe',
                 'check_jobid': '-1',
-                'testcase_name': check.name if check else 'reframe',
+                'check_info': check.info() if check else 'reframe',
                 'version': reframe.VERSION,
```
and here:
```
@@ -752,7 +814,7 @@ class RegressionTest:
                 self._perf_logfile: {
                     'level': 'DEBUG',
                     'format': '[%(asctime)s] reframe %(version)s: '
-                              '%(testcase_name)s '
+                              '%(check_info)s '
```

**Comment by vkarak** [comment]
Thanks @bcfriesen for reporting this. In 2.10, the `testcase_name` has changed to `check_info`, but unfortunately it has gone out undocumented... The solution is to simply rename `testcase_name` to `check_info` in your configuration file (logging configuration, specifically). Apologies for the inconvenience.

**Comment by bcfriesen** [comment]
Thanks @vkarak for being patient with my total Python illiteracy :-) Your solution worked, thanks.
