### ISSUE TITLE
dependence on git

### ISSUE THREAD

**Issue by haampie** [eth-cscs/reframe#1464]
When I install reframe through `pip` in minimal docker container, it seems it can only work when git is installed; probably it just tries to use git to get the current commit for the version number (?). Is git a hard dependency? If I could do without it would reduce the size of my docker image by 80MB.

It seems a `depends_on('git', type='run')` dep in the spack package is missing too: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/reframe/package.py.

**Comment by vkarak** [comment]
Good catch @haampie! Can you copy paste here the stack trace from ReFrame? I suspect where this is coming from.

**Comment by teojgo** [comment]
Thanks @haampie I can reproduce with a slim container without git:

```
Traceback (most recent call last):
  File "/usr/local/bin/reframe", line 18, in <module>
    import reframe.frontend.cli as cli  # noqa: F401, F403
  File "/usr/local/lib/python3.8/dist-packages/reframe/__init__.py", line 26, in <module>
    from reframe.core.pipeline import *     # noqa: F401, F403
  File "/usr/local/lib/python3.8/dist-packages/reframe/core/pipeline.py", line 25, in <module>
    import reframe.core.logging as logging
  File "/usr/local/lib/python3.8/dist-packages/reframe/core/logging.py", line 509, in <module>
    null_logger = LoggerAdapter()
  File "/usr/local/lib/python3.8/dist-packages/reframe/core/logging.py", line 403, in __init__
    'version': os_ext.reframe_version(),
  File "/usr/local/lib/python3.8/dist-packages/reframe/utility/os_ext.py", line 378, in reframe_version
    repo_hash = git_repo_hash()
  File "/usr/local/lib/python3.8/dist-packages/reframe/utility/os_ext.py", line 357, in git_repo_hash
    completed = run_command('git rev-parse %s' % branch,
  File "/usr/local/lib/python3.8/dist-packages/reframe/utility/os_ext.py", line 32, in run_command
    proc = run_command_async(cmd, shell=shell, start_new_session=True,
  File "/usr/local/lib/python3.8/dist-packages/reframe/utility/os_ext.py", line 67, in run_command_async
    return subprocess.Popen(args=cmd,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

**Comment by vkarak** [comment]
That's a bug of the framework in `os_ext.git_repo_has()`. We should handle the case when git is not available. Thanks for reporting!
