### ISSUE TITLE
reframe.core.exceptions.ConfigError: ... No module named 'lib.python3'

### ISSUE THREAD

**Issue by haampie** [eth-cscs/reframe#1465]
```
$ cat Dockerfile 
FROM ubuntu:18.04

RUN apt-get update -qq && \
    apt-get install -qq --no-install-recommends \
        git \
        python3 \
        python3-pip \
        python3-setuptools && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install reframe-hpc
$ docker build . -t reframe-3.1-pip
$ docker run reframe-3.1-pip reframe -v
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/reframe/core/config.py", line 197, in _create_from_python
    mod = util.import_module_from_file(filename)
  File "/usr/local/lib/python3.6/dist-packages/reframe/utility/__init__.py", line 75, in import_module_from_file
    return importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lib.python3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/reframe", line 21, in <module>
    cli.main()
  File "/usr/local/lib/python3.6/dist-packages/reframe/frontend/cli.py", line 410, in main
    os.path.join(reframe.INSTALL_PREFIX, 'reframe/core/settings.py')
  File "/usr/local/lib/python3.6/dist-packages/reframe/core/config.py", line 577, in load_config
    return _SiteConfig.create(filename)
  File "/usr/local/lib/python3.6/dist-packages/reframe/core/config.py", line 188, in create
    return cls._create_from_python(filename)
  File "/usr/local/lib/python3.6/dist-packages/reframe/core/config.py", line 203, in _create_from_python
    ) from e
reframe.core.exceptions.ConfigError: could not load Python configuration file: '/usr/local/lib/python3.6/dist-packages/reframe/core/settings.py': No module named 'lib.python3'
```

**Comment by haampie** [comment]
`pip3 install reframe-hpc==3.0` seems to be fine

**Comment by vkarak** [comment]
Thanks @haampie for reporting! It seems to be a problem in how we package 3.1.

**Comment by sabo** [comment]
I ran into a similar issue working in a venv. Installing it as editable (something like `pip3 install --user -e git+https://github.com/eth-cscs/reframe.git@3.1#egg=reframe-hpc`) worked for me

**Comment by teojgo** [comment]
This problem happens because https://github.com/eth-cscs/reframe/blob/51e2a0374ac097b6aeeaccf193b5fc409f81c273/reframe/utility/__init__.py#L29 
ends up inlcuding `lib.python3.6.dist-packages` as a prefix of the module name  and `.` in `python3.6` is treated as a package separator. 
This happends for standard python package installations with pip `site-packages` and for the debian specific `dist-packages`.
