### ISSUE TITLE
ReFrame 3.3 and above broke support for Lmod < 8.2

### ISSUE THREAD

**Issue by mand35** [eth-cscs/reframe#1648]
When using the latest revision of reframe OR v3.3 every test results in:

```
------------------------------------------------------------------------------
FAILURE INFO for HelloWorldTestSerial_cpp_dynamic
  * Test Description: C++ Hello World Serial Dynamic
  * System partition: ubelix:gpu
  * Environment: foss
  * Stage directory: ~/ReFrame/stage/ubelix/gpu/foss/HelloWorldTestSerial_cpp_dynamic
  * Node list: None
  * Job type: batch job (id=None)
  * Dependencies (conceptual): []
  * Dependencies (actual): []
  * Maintainers: ['VH', 'EK']
  * Failing phase: compile
  * Rerun with '-n HelloWorldTestSerial_cpp_dynamic -p foss --system ubelix:gpu'
  * Reason: name error: name 'os' is not defined
Traceback (most recent call last):
  File "/gpfs/homefs/id/id-svcrsitsm_conn/tmp/reframe/reframe/frontend/executors/__init__.py", line 250, in _safe_call
    return fn(*args, **kwargs)
  File "/gpfs/homefs/id/id-svcrsitsm_conn/tmp/reframe/reframe/core/pipeline.py", line 110, in _fn
    func(obj, *args, **kwargs)
  File "/gpfs/homefs/id/id-svcrsitsm_conn/tmp/reframe/reframe/core/pipeline.py", line 124, in _wrapped
    return fn(*args, **kwargs)
  File "/gpfs/homefs/id/id-svcrsitsm_conn/tmp/reframe/reframe/core/pipeline.py", line 1224, in compile
    trap_errors=True
  File "/gpfs/homefs/id/id-svcrsitsm_conn/tmp/reframe/reframe/core/schedulers/__init__.py", line 364, in prepare
    builder.write(runtime.emit_loadenv_commands(*environs))
  File "/gpfs/homefs/id/id-svcrsitsm_conn/tmp/reframe/reframe/core/runtime.py", line 235, in emit_loadenv_commands
    _, commands = loadenv(*environs)
  File "/gpfs/homefs/id/id-svcrsitsm_conn/tmp/reframe/reframe/core/runtime.py", line 216, in loadenv
    load_seq = modules_system.load_module(**mod, force=True)
  File "/gpfs/homefs/id/id-svcrsitsm_conn/tmp/reframe/reframe/core/modules.py", line 238, in load_module
    ret.append((m, self._load_module(m, force, collection)))
  File "/gpfs/homefs/id/id-svcrsitsm_conn/tmp/reframe/reframe/core/modules.py", line 252, in _load_module
    conflict_list = self._backend.conflicted_modules(module)
  File "/gpfs/homefs/id/id-svcrsitsm_conn/tmp/reframe/reframe/core/modules.py", line 850, in conflicted_modules
    output = self.execute('show', str(module))
  File "/gpfs/homefs/id/id-svcrsitsm_conn/tmp/reframe/reframe/core/modules.py", line 411, in execute
    exec_output = self._execute(cmd, *args)
  File "/gpfs/homefs/id/id-svcrsitsm_conn/tmp/reframe/reframe/core/modules.py", line 743, in _execute
    exec(completed.stdout, {}, namespace)
  File "<string>", line 1, in <module>
NameError: name 'os' is not defined
```
I build ReFrame using:

```
git clone https://github.com/eth-cscs/reframe.git
cd reframe
./bootstrap.sh
```
and tried running: 
`./bin/reframe -v -c ../prgenv/ -n HelloWorldTestSerial_cpp_dynamic -r -C ../settings.py`
where the test cases has `import os`:

```
head ../prgenv/helloworld.py
from datetime import datetime
import os
import reframe as rfm
import reframe.utility.sanity as sn


class HelloWorldBaseTest(rfm.RegressionTest):
    def __init__(self, variant, lang, linkage):
        self.linkage = linkage
```

I get the same effect when I rebuild as follow and rerun:

```
git checkout v3.3
rm -rf external/*
./bootstrap.sh
```  

BUT if I go back to v3.2 with the same procedure, the test runs fine. 

In my configuration this is using the system python, which seems to work fine with the os package:

```
$ head -n 1 ./bin/reframe
#!/usr/bin/env python3
$ /usr/bin/env python3
Python 3.6.8 (default, Apr  2 2020, 13:34:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.isdir('~')
True
```

In my defined environments:`foss` and `intel`, both results to the system python as above. 
Is there something I am missing?

**Comment by vkarak** [comment]
@mand35 Correct me if I'm wrong: you are using Lmod as a modules system, right?

**Comment by mand35** [comment]
@vkarak, yes, we are using lmod.

**Comment by vkarak** [comment]
Can you also share the configuration entry for the system and the environment?

**Comment by vkarak** [comment]
@mand35 Which LMod version are you using?

**Comment by mand35** [comment]
sure. LMOD version is 7.7.14 and the site configuration is:
```
site_configuration = {
    'systems': [
        {
            'name': 'generic',
            'descr': 'Generic example system',
            'hostnames': [
                'localhost'
            ],
            'partitions': [
                {
                    'name': 'login',
                    'scheduler': 'local',
                    'modules': [],
                    'access': [],
                    'environs': [
                        'builtin-gcc'
                    ],
                    'descr': 'Login nodes',
                    'launcher': 'local'
                }
            ]
        },
        {
            'name': 'ubelix',
            'descr': 'UniBE HPC system UBELiX',
            'hostnames': [
                'submit'
            ],
            'modules_system': 'lmod',
            'stagedir': '/storage/homefs/ms20e149/ReFrame/stage/',
            'outputdir': '/storage/homefs/ms20e149/ReFrame/output/',
            'resourcesdir': '/storage/homefs/ms20e149/ReFrame/resources',
            'partitions': [
                {
                    'name': 'login',
                    'scheduler': 'local',
                    'modules': [],
                    'access': [],
                    'environs': [
                        'builtin-gcc'
                    ],
                    'descr': 'Login nodes',
                    'launcher': 'local'
                },
                {
                    'name': 'mc',
                    'scheduler': 'slurm',
                    'modules': [],
                    'access': [],
                    'environs': [
                        'foss',
                        'intel',
                        'pgi'
                    ],
                    'descr': 'compute nodes',
                    'launcher': 'srun'
                },
                {
                    'name': 'gpu',
                    'scheduler': 'slurm',
                    'modules': [],
                    'access': [
                        '--partition=gpu',
                        '--gres=gpu:teslaP100:1'
                    ],
                    'environs': [
                        'foss',
                        'intel',
                        'pgi'
                    ],
                    'descr': 'gpu compute nodes',
                    'launcher': 'srun'
                }
            ]
        }
    ],
    'environments': [
        {
            'name': 'builtin',
            'cc': 'cc',
            'cxx': '',
            'ftn': ''
        },
        {
            'name': 'builtin-gcc',
            'cc': 'gcc',
            'cxx': 'g++',
            'ftn': 'gfortran'
        },
        {
            'name': 'foss',
            'modules': [
                'foss'
            ],
            'cc': 'mpicc',
            'cxx': 'mpic++',
            'ftn': 'mpifort'
        },
        {
            'name': 'intel',
            'modules': [
                'intel'
            ],
            'cc': 'mpiicc',
            'cxx': 'mpiicpc',
            'ftn': 'mpiifort'
        },
        {
            'name': 'pgi',
            'modules': [
                'PGI'
            ],
            'cc': 'pgcc',
            'cxx': 'pgc++',
            'ftn': 'pgf90'
        }
    ],
...
```

**Comment by vkarak** [comment]
Hi @mand35, I confirmed it. It's a bug and is due to the Lmod version. ReFrame 3.3 should work with Lmod >= 8 but we apparently broke it for older Lmod versions. In fact, we have changed the implementation of the module backends for 3.3, but we have tested only against more recent Lmod versions. Here is a Dockerfile that reproduces exactly the error you reported:

```dockerfile
#
# Execute this from the top-level ReFrame source directory
#

FROM ubuntu:20.04

ENV TZ=Europe/Zurich
ENV DEBIAN_FRONTEND=noninteractive
ENV _LMOD_VER=7.7.14

# ReFrame user
RUN useradd -ms /bin/bash rfmuser

# ReFrame requirements
RUN \
  apt-get -y update && \
  apt-get -y install ca-certificates && \
  update-ca-certificates && \
  apt-get -y install gcc && \
  apt-get -y install make && \
  apt-get -y install git && \
  apt-get -y install python3 python3-pip

# Required utilities
RUN apt-get -y install wget

# Install Lmod
RUN \
  apt-get -y install lua5.3 lua-bit32:amd64 lua-posix:amd64 lua-posix-dev liblua5.3-0:amd64 liblua5.3-dev:amd64 tcl tcl-dev tcl8.6 tcl8.6-dev:amd64 libtcl8.6:amd64 lua-filesystem:amd64 lua-filesystem-dev:amd64 && \
  wget -q https://github.com/TACC/Lmod/archive/${_LMOD_VER}.tar.gz -O lmod.tar.gz && \
  tar xzf lmod.tar.gz && \
  cd Lmod-${_LMOD_VER} && \
  ./configure && make install

ENV BASH_ENV=/usr/local/lmod/lmod/init/profile

USER rfmuser

# Install ReFrame from the current directory
COPY --chown=rfmuser . /home/rfmuser/reframe/

WORKDIR /home/rfmuser/reframe

RUN ./bootstrap.sh

CMD ["/bin/bash", "-c", "./test_reframe.py --rfm-user-config=ci-scripts/configs/lmod.py -v"]
```

**Comment by mand35** [comment]
Thanks a lot. Let me know if I can do something for you.
