### ISSUE TITLE
ReFrame PyPI installation is broken

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#1765]
From a clean environment:

```
python3 -m venv rfm_venv
source rfm_venv/bin/activate
pip install reframe-hpc
```

Trying to run `reframe -V` gives:

```
Traceback (most recent call last):
  File "/home/teojgo/rfm_venv/bin/reframe", line 19, in <module>
    import reframe.frontend.cli as cli  # noqa: F401, F403
  File "/home/teojgo/rfm_venv/lib/python3.8/site-packages/reframe/frontend/cli.py", line 23, in <module>
    import reframe.frontend.argparse as argparse
  File "/home/teojgo/rfm_venv/lib/python3.8/site-packages/reframe/frontend/argparse.py", line 6, in <module>
    import argcomplete
ModuleNotFoundError: No module named 'argcomplete'
```

**Comment by vkarak** [comment]
Duplicate of #1766.
