### ISSUE TITLE
Add option to bypass the check that modules exist

### ISSUE THREAD

**Issue by branfosj** [eth-cscs/reframe#1846]
On our system it is possible to submit from any node type to any other node type and we have modules that do not exist on all node types. This means that there is no one node where `module load foo` will work for all the modules that it is possible to load in a job. In the ReFrame job script preparation the existence of the module is tested and the job fails if the module cannot be loaded.

Can we have an option to skip that check?

Traceback:
```
Traceback (most recent call last):
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/frontend/executors/__init__.py", line 262, in _safe_call
    return fn(*args, **kwargs)
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/core/pipeline.py", line 110, in _fn
    func(obj, *args, **kwargs)
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/core/pipeline.py", line 1870, in run
    super().run.__wrapped__(self)
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/core/pipeline.py", line 124, in _wrapped
    return fn(*args, **kwargs)
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/core/pipeline.py", line 1358, in run
    'general/0/trap_job_errors'
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/core/schedulers/__init__.py", line 364, in prepare
    builder.write(runtime.emit_loadenv_commands(*environs))
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/core/runtime.py", line 237, in emit_loadenv_commands
    _, commands = loadenv(*environs)
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/core/runtime.py", line 215, in loadenv
    load_seq = modules_system.load_module(**mod, force=True)
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/core/modules.py", line 264, in load_module
    ret.append((m, self._load_module(m, collection, path, force)))
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/core/modules.py", line 278, in _load_module
    conflict_list = self._backend.conflicted_modules(module)
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/core/modules.py", line 671, in conflicted_modules
    output = self.execute_with_path('show', str(module), path=module.path)
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/core/modules.py", line 463, in execute_with_path
    return self.execute(cmd, *args)
  File "/rds/projects/2017/branfosj-rse/BEAR-git/reframe/.venv/lib64/python3.6/site-packages/reframe/core/modules.py", line 457, in execute
    raise EnvironError('could not execute module operation') from e
reframe.core.exceptions.EnvironError: could not execute module operation: command 'modulecmd python show Amber/20.9-AmberTools-20.14-fosscuda-2020a-Python-3.8.2' failed with exit code 0:
--- stdout ---
--- stdout ---
--- stderr ---
ModuleCmd_Display.c(151):ERROR:105: Unable to locate a modulefile for 'Amber/20.9-AmberTools-20.14-fosscuda-2020a-Python-3.8.2'
```

The referenced module here is only available on our GPU nodes and I was running ReFram on a non-GPU node.

**Comment by teojgo** [comment]
@branfosj Can you elaborate on this? Isn't the test supposed to fail if the module is not available? Furthermore you could customize the modules that you are loading based on the node type that you are running using [Pipeline Hooks](https://reframe-hpc.readthedocs.io/en/stable/regression_test_api.html?highlight=hooks#pipeline-hooks).

**Comment by branfosj** [comment]
@teojgo I am hitting this issue when the module is not available on the node I am running ReFrame on. However, the module is available on the node that the test will run on. And I can submit jobs from the node that ReFrame is running on to a node that can run the test.

I do not follow on how I'd use a pipeline hook to customise the modules being loaded. This still looks to hit the same issue that the module is not available on the node that ReFrame is running on.

**Comment by teojgo** [comment]
@branfosj Ok, I get it now, so the environment of the node where the job is submitted is different from the one that ReFrame is executing. As a temporary workaround you can use the `prerun_cmds` and do the module load there. But this is not optimal since ReFrame cannot track the environment in this case.
