### ISSUE TITLE
Unexpected error when disk quota is exceeded

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#1886]
```
./bin/reframe: run session stopped: attribute error: 'RegressionTask' object has no attribute 'case'
./bin/reframe: Traceback (most recent call last):
  File "/users/karakasv/Devel/reframe/reframe/frontend/executors/__init__.py", line 318, in finalize
    with open(jsonfile, 'w') as fp:
OSError: [Errno 122] Disk quota exceeded: '/users/karakasv/Devel/reframe/stage/tsa/cn/PrgEnv-gnu-nompi/NetCDFTest_cpp_dynamic/.rfm_testcase.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/karakasv/Devel/reframe/reframe/frontend/cli.py", line 968, in main
    runner.runall(testcases, restored_cases)
  File "/users/karakasv/Devel/reframe/reframe/frontend/executors/__init__.py", line 431, in runall
    self._runall(testcases)
  File "/users/karakasv/Devel/reframe/reframe/frontend/executors/__init__.py", line 504, in _runall
    self._policy.exit()
  File "/users/karakasv/Devel/reframe/reframe/frontend/executors/policies.py", line 540, in exit
    self._finalize_all()
  File "/users/karakasv/Devel/reframe/reframe/frontend/executors/policies.py", line 472, in _finalize_all
    self._finalize_task(task)
  File "/users/karakasv/Devel/reframe/reframe/frontend/executors/policies.py", line 482, in _finalize_task
    task.finalize()
  File "/users/karakasv/Devel/reframe/reframe/frontend/executors/__init__.py", line 322, in finalize
    f'could not dump test case {self.case}: {e}'
AttributeError: 'RegressionTask' object has no attribute 'case'
```

**Comment by teojgo** [comment]
The error comes from the fact that `case` is not a valid attribute for `RegressionTask`. It should be changed to `testcase`.
