### ISSUE TITLE
ReFrame fails when environment config is misused

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/reframe#1943]
https://gist.github.com/1f6c8910375375af3c78bf1882ce5547.git
This issue relates indirectly to https://github.com/eth-cscs/reframe/pull/1939

**Comment by jgphpc** [comment]
# reframe -c 0.py -r -p PrgEnv-gnu1
```
[ReFrame Setup]
  version:           3.6.0-dev.3+1ba2f7f0
  command:           '/home/ubuntu/reframe.git/bin/reframe --keep-stage -C /home/ubuntu/reframe.git/config/ubjg.py -c 0.py -r -p PrgEnv-gnu1'
  launched by:       ubuntu@ub21jg
  working directory: '/home/ubuntu/git/reframe.git/DEL/0'
  settings file:     '/home/ubuntu/reframe.git/config/ubjg.py'
  check search path: (R) '/home/ubuntu/git/reframe.git/DEL/0/0.py'
  stage directory:   '/home/ubuntu/git/reframe.git/DEL/0/stage'
  output directory:  '/home/ubuntu/git/reframe.git/DEL/0/output'

[==========] Running 1 check(s)
[==========] Started on Thu Apr 22 09:49:23 2021

[----------] started processing HelloTest (HelloTest)
[ RUN      ] HelloTest on ubu:login using PrgEnv-gnu1
[----------] finished processing HelloTest (HelloTest)

[----------] waiting for spawned checks to finish
[       OK ] (1/1) HelloTest on ubu:login using PrgEnv-gnu1 [compile: 4.436s run: 0.016s total: 4.464s]
[----------] all spawned checks have finished

[  PASSED  ] Ran 1/1 test case(s) from 1 check(s) (0 failure(s), 0 skipped)
```

# reframe -c 0.py -r -p PrgEnv-gnu3
```
SUMMARY OF FAILURES
------------------------------------------------------------------------------
FAILURE INFO for HelloTest
  * Test Description: HelloTest
  * System partition: ubu:login
  * Environment: PrgEnv-gnu3
  * Stage directory: /home/ubuntu/git/reframe.git/DEL/0/stage/ubu/login/PrgEnv-gnu3/HelloTest
  * Node list:
  * Job type: local (id=None)
  * Dependencies (conceptual): []
  * Dependencies (actual): []
  * Maintainers: []
  * Failing phase: compile
  * Rerun with '-n HelloTest -p PrgEnv-gnu3 --system ubu:login -r'
  * Reason: key error: 'collection'
Traceback (most recent call last):
  File "/home/ubuntu/reframe.git/reframe/frontend/executors/__init__.py", line 269, in _safe_call
    return fn(*args, **kwargs)
  File "/home/ubuntu/reframe.git/reframe/core/hooks.py", line 36, in _fn
    func(obj, *args, **kwargs)
  File "/home/ubuntu/reframe.git/reframe/core/pipeline.py", line 97, in _wrapped
    return fn(*args, **kwargs)
  File "/home/ubuntu/reframe.git/reframe/core/pipeline.py", line 1246, in compile
    self._build_job.prepare(
  File "/home/ubuntu/reframe.git/reframe/core/schedulers/__init__.py", line 364, in prepare
    builder.write(runtime.emit_loadenv_commands(*environs))
  File "/home/ubuntu/reframe.git/reframe/core/runtime.py", line 237, in emit_loadenv_commands
    _, commands = loadenv(*environs)
  File "/home/ubuntu/reframe.git/reframe/core/runtime.py", line 224, in loadenv
    m, mod['collection'], mod['path'],
KeyError: 'collection'
```

It is wrong to write the config file like this: https://gist.github.com/jgphpc/1f6c8910375375af3c78bf1882ce5547#file-ub-py-L75
but since reframe does not complain, it could be a bug.
