### ISSUE TITLE
find_modules can sometimes find the same module twice

### ISSUE THREAD

**Issue by akesandgren** [eth-cscs/reframe#2296]
This lmod output shows the situation when it happens:
```
b-an01 [~]$ ml load foss/2020b
b-an01 [~]$ ml avail SciPy-bundle

------------------------------------ /home/a/ake/easybuild/modules/all/MPI/GCC/10.2.0/OpenMPI/4.0.5 -------------------------------------
   SciPy-bundle/2020.11-Python-2.7.18

------------------------------------------ /hpc2n/eb/modules/all/MPI/GCC/10.2.0/OpenMPI/4.0.5 -------------------------------------------
   SciPy-bundle/2020.11-Python-2.7.18    SciPy-bundle/2020.11 (D)

```
I.e. I have both the system installed SciPy-bundle/2020.11-Python-2.7.18 and one in my own tree.

The end result is that I get:
```
ESC[33m/hpc2n/eb/software/ReFrame/3.9.1/bin/reframe: skipping test file '/afs/hpc2n.umu.se/home/a/ake/Projects/git-repos/reframe/hpc2n-checks/apps/python/numpy_check.py': name conflict error: test 'hpc2n_numpy_test___kebnekaise_bdw____foss_2020b____SciPy_bundle_2020_11_Python_2_7_18__' from '/afs/hpc2n.umu.se/home/a/ake/Projects/git-repos/reframe/hpc2n-checks/apps/python/numpy_check.py' is already defined in '/afs/hpc2n.umu.se/home/a/ake/Projects/git-repos/reframe/hpc2n-checks/apps/python/numpy_check.py' (rerun with '-v' for more information)ESC[0m
Traceback (most recent call last):
  File "/hpc2n/eb/software/ReFrame/3.9.1/lib/python3.8/site-packages/reframe/frontend/loader.py", line 236, in load_from_file
    return self.load_from_module(
  File "/hpc2n/eb/software/ReFrame/3.9.1/lib/python3.8/site-packages/reframe/frontend/loader.py", line 223, in load_from_module
    raise NameConflictError(
reframe.core.exceptions.NameConflictError: test 'hpc2n_numpy_test___kebnekaise_bdw____foss_2020b____SciPy_bundle_2020_11_Python_2_7_18__' from '/afs/hpc2n.umu.se/home/a/ake/Projects/git-repos/reframe/hpc2n-checks/apps/python/numpy_check.py' is already defined in '/afs/hpc2n.umu.se/home/a/ake/Projects/git-repos/reframe/hpc2n-checks/apps/python/numpy_check.py'
```

**Comment by vkarak** [comment]
Which one would you like to choose in this case? Would the first found be sufficient?

**Comment by akesandgren** [comment]
The one that the module system picks is the preferred one, since that is what non-reframe situation would give me, perhaps with a small warning about finding multiple ones.

**Comment by vkarak** [comment]
I think that this should not be a problem any more with the updated test naming scheme that does not form the names by stringifying the parameter values. Can you try setting `RFM_COMPACT_TEST_NAMES=y`. There is not much information that you will get with this naming scheme for the moment (we're working on that in #2248), but you should avoid the name conflict.
