### ISSUE TITLE
ReFrame complains about missing required variables for tests that are not selected

### ISSUE THREAD

**Issue by smoors** [eth-cscs/reframe#2330]
The following output shows that a single test is selected with `--name GMXBenchMEMMN`.
ReFrame complains that a required variable is missing for test GMXBenchMEMMC, which is not selected (and GMXBenchMEMMN does not depend on it).
This is not a big deal, as ReFrame happily continues with the GMXBenchMEMMN test, but the error message gives the impression that something is wrong, while it clearly isn't.
 
```
Run report saved in 'xxx/.reframe/reports/run-report.json'
Log file(s) saved in 'xxx/reframe/testremote/osu/reframe.log', 'xxx/reframe/testremote/osu/reframe.out'
[ReFrame Setup]
  version:           3.9.1
  command:           '/apps/brussel/CO7/skylake/software/ReFrame/3.9.1/bin/reframe --verbose --run --checkpath gromacs.py --setvar modules=GROMACS/2021.3-foss-2021a --setvar num_tasks=4 --setvar num_tasks_per_node=1 --setvar exclus
ive_access= --setvar valid_systems=hydra:skylake-mn-mpi-ib, --name GMXBenchMEMMN'
  launched by:       xxx
  working directory: 'xxx/reframe/testremote/gromacs_bench'
  settings file:     'xxx/reframe/testremote/config/config.py'
  check search path: (R) 'xxx/reframe/testremote/gromacs_bench/gromacs.py'
  stage directory:   'xxx/reframe/testremote/gromacs_bench/stage'
  output directory:  'xxx/reframe/testremote/gromacs_bench/output'

/apps/brussel/CO7/skylake/software/ReFrame/3.9.1/bin/reframe: skipping test 'GMXBenchMEMMC': attribute error: gromacs.py:53: required variable 'num_cpus_per_task' has not been set
        self.executable_opts += ['-nt', f'{self.num_cpus_per_task}']
 (rerun with '-v' for more information)
Traceback (most recent call last):
  File "/apps/brussel/CO7/skylake/software/ReFrame/3.9.1/lib/python3.6/site-packages/reframe/core/decorators.py", line 71, in instantiate_all
    ret.append(test(*args, **kwargs))
  File "/apps/brussel/CO7/skylake/software/ReFrame/3.9.1/lib/python3.6/site-packages/reframe/core/meta.py", line 514, in __call__
    obj.__init__(*args, **kwargs)
  File "/apps/brussel/CO7/skylake/software/ReFrame/3.9.1/lib/python3.6/site-packages/reframe/core/hooks.py", line 82, in _fn
    getattr(obj, h.__name__)()
  File "/apps/brussel/CO7/skylake/software/ReFrame/3.9.1/lib/python3.6/site-packages/reframe/core/hooks.py", line 32, in _fn
    func(*args, **kwargs)
  File "xxx/reframe/testremote/gromacs_bench/gromacs.py", line 53, in post_init
    self.executable_opts += ['-nt', f'{self.num_cpus_per_task}']
  File "/apps/brussel/CO7/skylake/software/ReFrame/3.9.1/lib/python3.6/site-packages/reframe/core/pipeline.py", line 1013, in __getattr__
    ) from None
AttributeError: required variable 'num_cpus_per_task' has not been set
```

**Comment by vkarak** [comment]
Hi @smoors, can you share your `gromacs.py` test?

**Comment by smoors** [comment]
@vkarak here it is, feel free to let me know if I'm doing anything stupid:
https://gist.github.com/smoors/3f99962e6d6d0e8d58a84963f6dbdd45

**Comment by vkarak** [comment]
@smoors This happens because ReFrame instantiates all the tests before applying any filters. This is explained [here](https://reframe-hpc.readthedocs.io/en/stable/pipeline.html). That means that any post-init hook will also be executed before test filtering, which is exactly what is happening in your case. A workaround would be to set the executable options in a pre-run hook. I can't see a better solution for the moment, unfortunately.
