### ISSUE TITLE
NameError: name 'value' is not defined

### ISSUE THREAD

**Issue by mand35** [eth-cscs/reframe#453]
I changed to the new ReFrame version Reframe version: 2.14-dev2
I changed quite some deprecated things, but now I end up with the following error in most of my test cases, even with simple tests I copied from cscs_tests, like hello_world and osu microbenchmark:
```
FAILURE INFO for alltoall_osu_microbenchmark
  * System partition: maui:compute
  * Environment: PrgEnv-cray
  * Stage directory: /scale_wlg_persistent/filesets/home/schoenherrm/projects/NeSI_ReFrame/stage/maui/compute/PrgEnv-cray/alltoall_osu_microbenchmark
  * Job type: batch job (id=2290)
  * Maintainers: ['Man']
  * Failing phase: performance
  * Reason: unexpected error: name 'value' is not defined
Traceback (most recent call last):
  File "/scale_wlg_persistent/filesets/home/schoenherrm/projects/NeSI_ReFrame/reframe/frontend/executors/__init__.py", line 58, in _safe_call
    return fn(*args, **kwargs)
  File "/scale_wlg_persistent/filesets/home/schoenherrm/projects/NeSI_ReFrame/reframe/core/pipeline.py", line 1048, in performance
    self.check_performance()
  File "/scale_wlg_persistent/filesets/home/schoenherrm/projects/NeSI_ReFrame/reframe/core/pipeline.py", line 1081, in check_performance
    value[tag] = evaluate(expr)
NameError: name 'value' is not defined
```
I am using 
```
python --version
Python 3.6.5 :: Anaconda, Inc.

```

**Comment by mand35** [comment]
Hi @vkarak, sorry for bothering you. No there was no conflict, but unfortunately I messed up. You are correct, after comparing again in more details I found the issue in my branch. 
Thanks for help.
