### ISSUE TITLE
Bad test crashes frontend

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#554]
```
[22:09:18] karakasv@daint102 reframe [master] $ ./bin/reframe -C config/cscs.py -c cscs-checks/ -R -l --system=leone
Command line: ./bin/reframe -C config/cscs.py -c cscs-checks/ -R -l --system=leone
Reframe version: 2.15-dev2
Launched by user: karakasv
Launched on host: daint102
Reframe paths
=============
    Check prefix      :
(R) Check search path : 'cscs-checks/'
    Stage dir prefix     : /users/karakasv/Devel/reframe/stage/
    Output dir prefix    : /users/karakasv/Devel/reframe/output/
    Perf. logging prefix : /users/karakasv/Devel/reframe/perflogs
./bin/reframe: unexpected error: 'leone'
Traceback (most recent call last):
  File "/users/karakasv/Devel/reframe/reframe/frontend/cli.py", line 377, in main
    checks_found = loader.load_all()
  File "/users/karakasv/Devel/reframe/reframe/frontend/loader.py", line 168, in load_all
    checks.extend(self.load_from_dir(d, self._recurse))
  File "/users/karakasv/Devel/reframe/reframe/frontend/loader.py", line 146, in load_from_dir
    self.load_from_dir(entry.path, recurse)
  File "/users/karakasv/Devel/reframe/reframe/frontend/loader.py", line 154, in load_from_dir
    checks.extend(self.load_from_file(entry.path))
  File "/users/karakasv/Devel/reframe/reframe/frontend/loader.py", line 139, in load_from_file
    return self.load_from_module(util.import_module_from_file(filename))
  File "/users/karakasv/Devel/reframe/reframe/frontend/loader.py", line 108, in load_from_module
    candidates = module._rfm_gettests()
  File "/users/karakasv/Devel/reframe/reframe/core/decorators.py", line 30, in _instantiate
    ret.append(cls(*args))
  File "/users/karakasv/Devel/reframe/cscs-checks/mch/collectives_halo.py", line 101, in __init__
    'default': 0.0138493
  File "/users/karakasv/Devel/reframe/cscs-checks/mch/collectives_halo.py", line 65, in __init__
    ref = bench_reference[sysname][variant]
KeyError: 'leone'
```

**Comment by vkarak** [comment]
I think this issue is more complicated. On one hand we want the test to fail with a stack trace if there is a programming error. On the other hand, such invocation is valid, but the test crashes, because simply does not support this system. I don’t know what the correct behaviour is.

**Comment by victorusu** [comment]
This is a very interesting issue. I think we should
1. Print a warning on reframe.out stating that we are skipping this test
2. Print the traceback to reframe.log

Having said that, I thing we should fixed the test too.
