### ISSUE TITLE
Undefined variable on `core/schedulers/slurm.py` in current master (reframe-2.16-dev1)

### ISSUE THREAD

**Issue by rsarm** [eth-cscs/reframe#636]
The variable `node_match` is used [here](https://github.com/eth-cscs/reframe/blob/8cfdbbef6ec776535f7e31363dd1819069cb39ae/reframe/core/schedulers/slurm.py#L301) but it hasn't been defined:
```
$> reframe -r -c ../../prgenv/ulimit_check.py 
Command line: /users/sarafael/bin/reframe --config-file /users/sarafael/git/reframe/config/cscs.py -r -c ../../prgenv/ulimit_check.py
Reframe version: 2.16-dev1
Launched by user: sarafael
Launched on host: dom101
Reframe paths
=============
    Check prefix      : 
    Check search path : '../../prgenv/ulimit_check.py'
    Stage dir prefix     : /users/sarafael/git/reframe/cscs-checks/apps/tensorflow/stage/
    Output dir prefix    : /users/sarafael/git/reframe/cscs-checks/apps/tensorflow/output/
    Perf. logging prefix : /users/sarafael/git/reframe/cscs-checks/apps/tensorflow/perflogs
[==========] Running 1 check(s)
[==========] Started on Thu Dec 20 16:07:56 2018 

[----------] started processing UlimitCheck (Checking the output of ulimit -s in node.)
[ RUN      ] UlimitCheck on dom:gpu using PrgEnv-cray
[     FAIL ] UlimitCheck on dom:gpu using PrgEnv-cray
[ RUN      ] UlimitCheck on dom:gpu using PrgEnv-gnu
^C[     FAIL ] UlimitCheck on dom:gpu using PrgEnv-gnu
[  FAILED  ] Ran 2 test case(s) from 1 check(s) (2 failure(s))
[==========] Finished on Thu Dec 20 16:08:22 2018 

==============================================================================
SUMMARY OF FAILURES
------------------------------------------------------------------------------
FAILURE INFO for UlimitCheck 
  * System partition: dom:gpu
  * Environment: PrgEnv-cray
  * Stage directory: /users/sarafael/git/reframe/cscs-checks/apps/tensorflow/stage/dom/gpu/PrgEnv-cray/UlimitCheck
  * Job type: batch job (id=908679)
  * Maintainers: ['RS', 'VK']
  * Failing phase: wait
  * Reason: unexpected error: name 'node_match' is not defined
Traceback (most recent call last):
  File "/users/sarafael/git/reframe/reframe/frontend/executors/__init__.py", line 58, in _safe_call
    return fn(*args, **kwargs)
  File "/users/sarafael/git/reframe/reframe/core/pipeline.py", line 1073, in wait
    self._job.wait()
  File "/users/sarafael/git/reframe/reframe/core/schedulers/slurm.py", line 332, in wait
    self._update_state()
  File "/users/sarafael/git/reframe/reframe/core/schedulers/slurm.py", line 266, in _update_state
    self._cancel_if_blocked()
  File "/users/sarafael/git/reframe/reframe/core/schedulers/slurm.py", line 281, in _cancel_if_blocked
    self._check_and_cancel(completed.stdout)
  File "/users/sarafael/git/reframe/reframe/core/schedulers/slurm.py", line 301, in _check_and_cancel
    node_names = node_match['node_names']
NameError: name 'node_match' is not defined
```

**Comment by rsarm** [comment]
The error shows up only if the job is waiting because of `ReqNodeNotAvail`.
