### ISSUE TITLE
Unsupported operand types for +: SequenceView and list

### ISSUE THREAD

**Issue by sebkelle1** [eth-cscs/reframe#736]
This bug was recently introduced, breaking the HPCG and likwid checks,
version 98cbb53 works for HPCG.

`FAILURE INFO for HPCGCheckMKL 
  * System partition: dom:gpu
  * Environment: PrgEnv-intel
  * Stage directory: /scratch/snx3000tds/sebkelle/stage/dom/gpu/PrgEnv-intel/HPCGCheckMKL
  * Job type: batch job (id=None)
  * Maintainers: ['SK']
  * Failing phase: run
  * Reason: unexpected error: unsupported operand type(s) for +: 'SequenceView' and 'list'
Traceback (most recent call last):
  File "/project/csstaff/sebkelle/soft/reframe/reframe/frontend/executors/__init__.py", line 125, in _safe_call
    return fn(*args, **kwargs)
  File "/project/csstaff/sebkelle/soft/reframe/reframe/core/pipeline.py", line 1044, in run
    self._job.prepare(commands, environs, login=True)
  File "/project/csstaff/sebkelle/soft/reframe/reframe/core/schedulers/slurm.py", line 100, in prepare
    super().prepare(commands, environs, **gen_opts)
  File "/project/csstaff/sebkelle/soft/reframe/reframe/core/schedulers/__init__.py", line 231, in prepare
    guessed_num_tasks = self.guess_num_tasks()
  File "/project/csstaff/sebkelle/soft/reframe/reframe/core/schedulers/__init__.py", line 274, in guess_num_tasks
    self.sched_access + self.options)
TypeError: unsupported operand type(s) for +: 'SequenceView' and 'list'
`

**Comment by vkarak** [comment]
@sebkelle1 This is a duplicate fo #728 and is fixed in #729.
