### ISSUE TITLE
Problem handling the decaying polling rate in the asynchronous execution policy

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#77]
An error such as the following can appear:

```
./bin/reframe: unexpected error: math domain error
Traceback (most recent call last):
  File "/scratch/shared/leone/jenscscs/reframe-ci-leone-5d81168/reframe/frontend/cli.py", line 413, in main
    runner.runall(checks_matched, system)
  File "/scratch/shared/leone/jenscscs/reframe-ci-leone-5d81168/reframe/frontend/executors/__init__.py", line 176, in runall
    self._runall(checks, system)
  File "/scratch/shared/leone/jenscscs/reframe-ci-leone-5d81168/reframe/frontend/executors/__init__.py", line 246, in _runall
    self._policy.exit()
  File "/scratch/shared/leone/jenscscs/reframe-ci-leone-5d81168/reframe/frontend/executors/policies.py", line 288, in exit
    desired_rate = pollrate(t_elapsed, real_rate)
  File "/scratch/shared/leone/jenscscs/reframe-ci-leone-5d81168/reframe/frontend/executors/policies.py", line 88, in __call__
    self._init_poll_fn(init_rate)
  File "/scratch/shared/leone/jenscscs/reframe-ci-leone-5d81168/reframe/frontend/executors/policies.py", line 82, in _init_poll_fn
    self._c = math.log(self._a / (self._thres*self._b)) / self._decay
ValueError: math domain error
```
Problem can be reproduced on Leone.

Internal issue: https://madra.cscs.ch/scs/reframe/issues/580

**Comment by teojgo** [comment]
The bug lies in the calculation of  `self._a` which can become negative. This happens when `self._b` which is initialized with `self._min_rate` is larger than the given `init_rate`.

**Comment by teojgo** [comment]
I suggest checking `self_a` for values lower than 0 and assign a minimum value in that case.
