### ISSUE TITLE
ReFrame crashes if a test without a description is executed

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#868]
Example test:

```python
import os

import reframe as rfm
import reframe.utility.sanity as sn


@rfm.parameterized_test(['serial'], ['cuda'], ['openacc'])
class MiniAppTest(rfm.RegressionTest):
    def __init__(self, variant):
        self.valid_systems = ['daint:gpu']
        self.sourcesdir = os.path.join('../solutions', variant)
        if variant == 'cuda':
            self.valid_prog_environs = ['PrgEnv-gnu']
        elif variant == 'openacc':
            self.valid_prog_environs = ['PrgEnv-pgi']
        elif variant == 'serial':
            self.valid_prog_environs = ['PrgEnv-gnu', 'PrgEnv-pgi']

        self.executable = './main'
        self.executable_opts = ['256', '256', '100', '0.01']
        self.sanity_patterns = sn.assert_found(r'.+')
        self.perf_patterns = {
            'exec_time': sn.extractsingle(r'simulation took (\S+) seconds',
                                          self.stdout, 1, float),
            'perf': sn.extractsingle(r'at a rate of (\S+) iters/second',
                                     self.stdout, 1, float)
        }
        self.reference = {
            'daint:gpu': {
                'exec_time': (0, None, None, 's'),
                'perf': (0, None, None, 'iters/s')
            },
            '*': {
                'exec_time': (0, None, None, 's'),
                'perf': (0, None, None, 'iters/s')
            }
        }
```

Stacktrace

```
/apps/common/UES/jenkins/SLES12/easybuild/software/reframe/2.17/bin/reframe: unexpected error: MiniAppTest object has no attribute 'descr'
Traceback (most recent call last):
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/reframe/2.17/reframe/frontend/cli.py", line 535, in main
    runner.runall(checks_matched)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/reframe/2.17/reframe/frontend/executors/__init__.py", line 176, in runall
    self._runall(checks)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/reframe/2.17/reframe/frontend/executors/__init__.py", line 229, in _runall
    self._policy.enter_check(c)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/reframe/2.17/reframe/frontend/executors/__init__.py", line 312, in enter_check
    'started processing %s (%s)' % (check.name, check.descr)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/reframe/2.17/reframe/core/fields.py", line 30, in __get__
    (objtype.__name__, self._name)) from None
AttributeError: MiniAppTest object has no attribute 'descr'
```

This happens for both execution policies.

**Comment by vkarak** [comment]
This is invalid. The `super().__init__()` is missing. Another argument towards the new enhanced syntax ;-)
