### ISSUE TITLE
Framework crashes when trying to list a directory when system auto-detection fails

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#88]
Reproduce as:

```
./reframe.py -c foo -l
```

Crash output
```
--- Logging error ---
Traceback (most recent call last):
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'testcase_name'
Call stack:
  File "./reframe.py", line 6, in <module>
    cli.main()
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/cli.py", line 225, in main
    system = autodetect_system(site_config)
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/loader.py", line 317, in autodetect_system
    hostname = os_ext.run_command('cat /etc/xthostname', check=True).stdout
  File "/users/karakasv/Devel/reframe.public/reframe/utility/os.py", line 22, in run_command
    proc = run_command_async(cmd, shell=shell, start_new_session=True)
  File "/users/karakasv/Devel/reframe.public/reframe/utility/os.py", line 67, in run_command_async
    getlogger().debug('executing OS command: ' + cmd)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 1628, in debug
    self.log(DEBUG, msg, *args, **kwargs)
  File "/users/karakasv/Devel/reframe.public/reframe/core/logging.py", line 225, in log
    super().log(level, msg, *args, **kwargs)
Message: 'executing OS command: cat /etc/xthostname'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'testcase_name'
Call stack:
  File "./reframe.py", line 6, in <module>
    cli.main()
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/cli.py", line 227, in main
    printer.error("could not auto-detect system. Please specify "
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/printer.py", line 110, in error
    self._logger.error('%s: %s' % (sys.argv[0], msg))
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 1651, in error
    self.log(ERROR, msg, *args, **kwargs)
  File "/users/karakasv/Devel/reframe.public/reframe/core/logging.py", line 225, in log
    super().log(level, msg, *args, **kwargs)
Message: "./reframe.py: could not auto-detect system. Please specify it manually using the `--system' option."
Arguments: ()
./reframe.py: could not auto-detect system. Please specify it manually using the `--system' option.
--- Logging error ---
Traceback (most recent call last):
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'testcase_name'
Call stack:
  File "./reframe.py", line 6, in <module>
    cli.main()
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/cli.py", line 229, in main
    list_supported_systems(site_config.systems.values(), printer)
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/cli.py", line 28, in list_supported_systems
    printer.info('List of supported systems:')
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/printer.py", line 113, in info
    self._logger.info(msg)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 1634, in info
    self.log(INFO, msg, *args, **kwargs)
  File "/users/karakasv/Devel/reframe.public/reframe/core/logging.py", line 225, in log
    super().log(level, msg, *args, **kwargs)
Message: 'List of supported systems:'
Arguments: ()
List of supported systems:
--- Logging error ---
Traceback (most recent call last):
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'testcase_name'
Call stack:
  File "./reframe.py", line 6, in <module>
    cli.main()
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/cli.py", line 229, in main
    list_supported_systems(site_config.systems.values(), printer)
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/cli.py", line 30, in list_supported_systems
    printer.info('    %s' % s)
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/printer.py", line 113, in info
    self._logger.info(msg)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 1634, in info
    self.log(INFO, msg, *args, **kwargs)
  File "/users/karakasv/Devel/reframe.public/reframe/core/logging.py", line 225, in log
    super().log(level, msg, *args, **kwargs)
Message: "    generic (partitions: ['login'])"
Arguments: ()
    generic (partitions: ['login'])
[17:49:48] karakasv@dom101 reframe.public [master] $ ./reframe.py -c foo -l
--- Logging error ---
Traceback (most recent call last):
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'testcase_name'
Call stack:
  File "./reframe.py", line 6, in <module>
    cli.main()
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/cli.py", line 225, in main
    system = autodetect_system(site_config)
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/loader.py", line 317, in autodetect_system
    hostname = os_ext.run_command('cat /etc/xthostname', check=True).stdout
  File "/users/karakasv/Devel/reframe.public/reframe/utility/os.py", line 22, in run_command
    proc = run_command_async(cmd, shell=shell, start_new_session=True)
  File "/users/karakasv/Devel/reframe.public/reframe/utility/os.py", line 67, in run_command_async
    getlogger().debug('executing OS command: ' + cmd)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 1628, in debug
    self.log(DEBUG, msg, *args, **kwargs)
  File "/users/karakasv/Devel/reframe.public/reframe/core/logging.py", line 225, in log
    super().log(level, msg, *args, **kwargs)
Message: 'executing OS command: cat /etc/xthostname'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'testcase_name'
Call stack:
  File "./reframe.py", line 6, in <module>
    cli.main()
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/cli.py", line 227, in main
    printer.error("could not auto-detect system. Please specify "
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/printer.py", line 110, in error
    self._logger.error('%s: %s' % (sys.argv[0], msg))
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 1651, in error
    self.log(ERROR, msg, *args, **kwargs)
  File "/users/karakasv/Devel/reframe.public/reframe/core/logging.py", line 225, in log
    super().log(level, msg, *args, **kwargs)
Message: "./reframe.py: could not auto-detect system. Please specify it manually using the `--system' option."
Arguments: ()
./reframe.py: could not auto-detect system. Please specify it manually using the `--system' option.
--- Logging error ---
Traceback (most recent call last):
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'testcase_name'
Call stack:
  File "./reframe.py", line 6, in <module>
    cli.main()
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/cli.py", line 229, in main
    list_supported_systems(site_config.systems.values(), printer)
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/cli.py", line 28, in list_supported_systems
    printer.info('List of supported systems:')
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/printer.py", line 113, in info
    self._logger.info(msg)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 1634, in info
    self.log(INFO, msg, *args, **kwargs)
  File "/users/karakasv/Devel/reframe.public/reframe/core/logging.py", line 225, in log
    super().log(level, msg, *args, **kwargs)
Message: 'List of supported systems:'
Arguments: ()
List of supported systems:
--- Logging error ---
Traceback (most recent call last):
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'testcase_name'
Call stack:
  File "./reframe.py", line 6, in <module>
    cli.main()
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/cli.py", line 229, in main
    list_supported_systems(site_config.systems.values(), printer)
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/cli.py", line 30, in list_supported_systems
    printer.info('    %s' % s)
  File "/users/karakasv/Devel/reframe.public/reframe/frontend/printer.py", line 113, in info
    self._logger.info(msg)
  File "/apps/common/UES/jenkins/SLES12/easybuild/software/Python-bare/3.6.2/lib/python3.6/logging/__init__.py", line 1634, in info
    self.log(INFO, msg, *args, **kwargs)
  File "/users/karakasv/Devel/reframe.public/reframe/core/logging.py", line 225, in log
    super().log(level, msg, *args, **kwargs)
Message: "    generic (partitions: ['login'])"
Arguments: ()
    generic (partitions: ['login'])
```

**Comment by vkarak** [comment]
It seems that the logging framework is broken.

**Comment by vkarak** [comment]
`./reframe.py -l` also fails and is not caught by the unit tests, while it should have been.
