### ISSUE TITLE
MpipCheck error on Kesch with release 2.19

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/reframe#926]
ReFrame on Kesch (2.19) reports the message below:
```
./bin/reframe: skipping test due to errors: MpipCheck: use `-v' for more information
```
See https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-kesch-production-daily/detail/reframe-kesch-production-daily/165/pipeline/

Using `-v` as suggested gives the following:
```
  FILE: /appsmnt/escha/UES/jenkins/RH7.5/generic/easybuild/software/reframe/2.19/checks/tools/profiling_and_debugging/mpip_mpi_omp.py:70
Traceback (most recent call last):
  File "/appsmnt/escha/UES/jenkins/RH7.5/generic/easybuild/software/reframe/2.19/reframe/core/decorators.py", line 40, in _instantiate_all
    ret.append(_instantiate(cls, args))
  File "/appsmnt/escha/UES/jenkins/RH7.5/generic/easybuild/software/reframe/2.19/reframe/core/decorators.py", line 23, in _instantiate
    return cls(*args)
  File "/appsmnt/escha/UES/jenkins/RH7.5/generic/easybuild/software/reframe/2.19/checks/tools/profiling_and_debugging/mpip_mpi_omp.py", line 70, in __init__
    self.rpt_file, 'mpi_isendline'), mpi_isendline),
UnboundLocalError: local variable 'mpi_isendline' referenced before assignment
```

**Comment by vkarak** [comment]
@lucamar There is an error in this test. All tests are loaded first (i.e., their `__init__()` is executed) regardless of the current system and they get filtered afterwards. So each test must be "generic" in its `__init__()` method.

**Comment by vkarak** [comment]
@lucamar I will move that to JIRA.
