### ISSUE TITLE
reframe 2.18 installation with easybuild on my laptop not working

### ISSUE THREAD

**Issue by alchemroz** [eth-cscs/reframe#963]
Dear all, 
              I installed Reframe 2.18 with EasyBuild in my laptop using the "local" partition. I got the error in attachment.

[log_reframe_ex_1.txt](https://github.com/eth-cscs/reframe/files/3713748/log_reframe_ex_1.txt)

 I add also my current settings.py. 

[settings.py.txt](https://github.com/eth-cscs/reframe/files/3713761/settings.py.txt)

What is going wrong ? 

Thanks for the help,

**Comment by vkarak** [comment]
Hi @alchemroz, it seems that you are using the tutorial examples from the master. We have introduced a new syntax for 2.20 (the old is still valid), but the `tutorial` examples from the master use that. I'd say either use the latest reframe version from the master or use the tutorial examples from version 2.18:

```
git clone https://github.com/eth-cscs/reframe.git
git checkout v2.18
```

**Comment by vkarak** [comment]
For easy reference, I am pasting here inline your files:

- Output:
```
[simone@NSMAROCCH204664 reframe-test]$ reframe -c tutorial/example1.py -r

Command line: /home/simone/EasyBuild_INSTALL/software/ReFrame/2.18/bin/reframe -c tutorial/example1.py -r
Reframe version: 2.18
Launched by user: simone
Launched on host: NSMAROCCH204664
Reframe paths
=============
    Check prefix      : 
    Check search path : 'tutorial/example1.py'
    Stage dir prefix     : /home/simone/Documents/reframe-test/stage/
    Output dir prefix    : /home/simone/Documents/reframe-test/output/
    Perf. logging prefix : /home/simone/Documents/reframe-test/perflogs
[==========] Running 1 check(s)
[==========] Started on Thu Oct 10 19:02:07 2019 

[----------] started processing Example1Test (Simple matrix-vector multiplication example)
[ [32mRUN     [0m ] Example1Test on PdL_CINECA:OS_naked using builtin-gcc
Traceback (most recent call last):
  File "/home/simone/EasyBuild_INSTALL/software/ReFrame/2.18/bin/reframe", line 4, in <module>
    __import__('pkg_resources').run_script('ReFrame-HPC==2.18', 'reframe')
  File "/home/simone/EasyBuild_INSTALL/software/setuptools/41.0.1-py3/lib/python3.6/site-packages/setuptools-41.0.1-py3.6.egg/pkg_resources/__init__.py", line 666, in run_script
  File "/home/simone/EasyBuild_INSTALL/software/setuptools/41.0.1-py3/lib/python3.6/site-packages/setuptools-41.0.1-py3.6.egg/pkg_resources/__init__.py", line 1453, in run_script
  File "/home/simone/EasyBuild_INSTALL/software/ReFrame/2.18/lib/python3.6/site-packages/ReFrame_HPC-2.18-py3.6.egg/EGG-INFO/scripts/reframe", line 5, in <module>
    cli.main()
  File "/home/simone/EasyBuild_INSTALL/software/ReFrame/2.18/lib/python3.6/site-packages/ReFrame_HPC-2.18-py3.6.egg/reframe/frontend/cli.py", line 565, in main
    printer.error(format_exception(*sys.exc_info()))
  File "/home/simone/EasyBuild_INSTALL/software/ReFrame/2.18/lib/python3.6/site-packages/ReFrame_HPC-2.18-py3.6.egg/reframe/core/logging.py", line 474, in error
    super().error(message, *args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1653, in error
    self.log(ERROR, msg, *args, **kwargs)
  File "/home/simone/EasyBuild_INSTALL/software/ReFrame/2.18/lib/python3.6/site-packages/ReFrame_HPC-2.18-py3.6.egg/reframe/core/logging.py", line 457, in log
    super().log(level, msg, *args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1673, in log
    msg, kwargs = self.process(msg, kwargs)
  File "/home/simone/EasyBuild_INSTALL/software/ReFrame/2.18/lib/python3.6/site-packages/ReFrame_HPC-2.18-py3.6.egg/reframe/core/logging.py", line 446, in process
    self._update_check_extras()
  File "/home/simone/EasyBuild_INSTALL/software/ReFrame/2.18/lib/python3.6/site-packages/ReFrame_HPC-2.18-py3.6.egg/reframe/core/logging.py", line 413, in _update_check_extras
    self.extra['check_info'] = self.check.info()
  File "/home/simone/EasyBuild_INSTALL/software/ReFrame/2.18/lib/python3.6/site-packages/ReFrame_HPC-2.18-py3.6.egg/reframe/core/pipeline.py", line 788, in info
    if self.current_partition:
  File "/home/simone/EasyBuild_INSTALL/software/ReFrame/2.18/lib/python3.6/site-packages/ReFrame_HPC-2.18-py3.6.egg/reframe/core/pipeline.py", line 664, in current_partition
    return self._current_partition
  File "/home/simone/EasyBuild_INSTALL/software/ReFrame/2.18/lib/python3.6/site-packages/ReFrame_HPC-2.18-py3.6.egg/reframe/core/fields.py", line 30, in __get__
    (objtype.__name__, self._name)) from None
AttributeError: Example1Test object has no attribute '_current_partition'
```

- Settings:

```python
#
# ReFrame generic settings
#


class ReframeSettings:
    reframe_module = None
    job_poll_intervals = [1, 2, 3]
    job_submit_timeout = 60
    checks_path = ['checks/']
    checks_path_recurse = True
    site_configuration = {
        'systems': {
            # Generic system used also in unit tests
            'PdL_CINECA': {
                'descr': 'PdL in CINECA',

                # Adjust to your system's hostname
                'hostnames': ['NSMAROCCH204664'],
                'modules_system': 'lmod',
                'prefix': '.',
                'partitions': {
                    'OS_naked': {
                        'scheduler': 'local',
                        'modules': [],
                        'access':  [],
                        'environs': ['builtin-gcc'],
                        'descr': 'OS naked without modules'
                    }
                }
            }
        },

        'environments': {
            '*': {
                'builtin': {
                    'type': 'ProgEnvironment',
                    'cc':  'cc',
                    'cxx': '',
                    'ftn': '',
                },

                'builtin-gcc': {
                    'type': 'ProgEnvironment',
                    'cc':  'gcc',
                    'cxx': 'g++',
                    'ftn': 'gfortran',
                }
            }
        }
    }

    logging_config = {
        'level': 'DEBUG',
        'handlers': [
            {
                'type': 'file',
                'name': 'reframe.log',
                'level': 'DEBUG',
                'format': '[%(asctime)s] %(levelname)s: '
                          '%(check_info)s: %(message)s',
                'append': False,
            },

            # Output handling
            {
                'type': 'stream',
                'name': 'stdout',
                'level': 'INFO',
                'format': '%(message)s'
            },
            {
                'type': 'file',
                'name': 'reframe.out',
                'level': 'INFO',
                'format': '%(message)s',
                'append': False,
            }
        ]
    }

    perf_logging_config = {
        'level': 'DEBUG',
        'handlers': [
            {
                'type': 'filelog',
                'prefix': '%(check_system)s/%(check_partition)s',
                'level': 'INFO',
                'format': (
                    '%(asctime)s|reframe %(version)s|'
                    '%(check_info)s|jobid=%(check_jobid)s|'
                    '%(check_perf_var)s=%(check_perf_value)s|'
                    'ref=%(check_perf_ref)s '
                    '(l=%(check_perf_lower_thres)s, '
                    'u=%(check_perf_upper_thres)s)|'
                    '%(check_perf_unit)s'
                ),
                'append': True
            }
        ]
    }


settings = ReframeSettings()
```

**Comment by alchemroz** [comment]
Dear @vkarak, 
                        thank you for the help. Using the tutorial version 2.18 everything worked nicely. 

[simone@NSMAROCCH204664 reframe-test]$ reframe -c tutorial/example1.py -r
Command line: /home/simone/EasyBuild_INSTALL/software/ReFrame/2.18/bin/reframe -c tutorial/example1.py -r
Reframe version: 2.18
Launched by user: simone
Launched on host: NSMAROCCH204664
Reframe paths
=============
    Check prefix      : 
    Check search path : 'tutorial/example1.py'
    Stage dir prefix     : /home/simone/Documents/reframe-test/stage/
    Output dir prefix    : /home/simone/Documents/reframe-test/output/
    Perf. logging prefix : /home/simone/Documents/reframe-test/perflogs
[==========] Running 1 check(s)
[==========] Started on Fri Oct 11 10:27:41 2019 

[----------] started processing Example1Test (Simple matrix-vector multiplication example)
[ RUN      ] Example1Test on PdL_CINECA:OS_naked using builtin-gcc
[       OK ] Example1Test on PdL_CINECA:OS_naked using builtin-gcc
[----------] finished processing Example1Test (Simple matrix-vector multiplication example)

[  PASSED  ] Ran 1 test case(s) from 1 check(s) (0 failure(s))
[==========] Finished on Fri Oct 11 10:27:41 2019 

I noticed that the only change in the example1 between 2.18 and 2.19 is

  super().__init__()

So far I will keep using ReFrame version 2.18 because is the only one already available inside EasyBuild. If I need some features of 2.19 I will ask some help to the EasyBuild support. 

Many thanks

**Comment by vkarak** [comment]
@alchemroz In the latest master, pre 2.20, we have also done several improvements in the syntax that actually make redundant the need to override `setup()`. You can check the latest documentation here: https://reframe-hpc.readthedocs.io/en/latest/

**Comment by alchemroz** [comment]
Hello @vkarak , 
                          I installed EasyBuild 4.0 and I looked for Reframe 2.19 but neither in 
/home/simone/EasyBuild_INSTALL/software/EasyBuild/4.0.0/easybuild/easyconfigs/r/ReFrame

or

https://easybuild.readthedocs.io/en/latest/version-specific/Supported_software.html#list-software-reframe-674

is possible to find the easybuild installer of ReFrame 2.19. Probably they plan to add it in one of the upcoming release ?

Thanks for the updates about ReFrame 2.20

Bests

**Comment by vkarak** [comment]
It seems it was added just after the 4.0.0 release. It is scheduled for 4.0.1 though: https://github.com/easybuilders/easybuild-easyconfigs/pull/8956

But, in any case, you can just grab the easyconfig file for 2.19 and install it.
